routes/admin.php
<?php

// Route::group(
// [
// 	'prefix' => LaravelLocalization::setLocale(),
// 	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
// ], function(){
//


    Route::get('power', 'Admin\AdminAuth@login');

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {


            Config::set('auth.defines', 'admin');
             app()->setLocale('ar');



            //================ Auth ================
//            Route::get('login', 'AdminAuth@login');
            Route::post('power', 'AdminAuth@dologin');
            Route::get('forgot/password', 'AdminAuth@forgot_password');
            Route::post('forgot/password', 'AdminAuth@forgot_password_post');
            Route::get('reset/password/{token}', 'AdminAuth@reset_password');
            Route::post('reset/password/{token}', 'AdminAuth@reset_password_final');


        //********************* after login *********************
            Route::group(['middleware' => 'admin:admin'], function () {


                Route::get('/', function () {
                        return view('admin.index');
                    });



               //================ settings ================
                Route::get('settings', 'SettingController@setting_page');
                Route::post('operate_page', 'SettingController@operate_page')->name('operate_page');;
                Route::post('settings', 'SettingController@send_settings')->name('send_settings');




                //================ admin ================
                Route::resource('admin', 'AdminController');
                Route::delete('admin/destroy/all', 'AdminController@multi_delete')->name('delete_all_admin');


                //================ site_text ================
                Route::resource('site_text', 'SiteTextController');
                Route::delete('site_text/destroy/all', 'SiteTextController@multi_delete')->name('delete_all_site_text');


                //================ banner ================
                Route::resource('banner', 'BannerController');
                Route::delete('banner/destroy/all', 'BannerController@multi_delete')->name('delete_all_banner');


                //================== level ==================
                Route::resource('level', 'LevelController');
                Route::delete('level/destroy/all', 'LevelController@multi_delete')->name('delete_all_level');


                //================== course ==================
                Route::resource('course', 'CourseController');
                Route::delete('course/destroy/all', 'CourseController@multi_delete')->name('delete_all_course');


                //================ open_course ===============
                Route::resource('open_course', 'OpenCourseController');
                Route::delete('open_course/destroy/all', 'OpenCourseController@multi_delete')->name('delete_all_open_course');


                //================== team ==================
                Route::resource('team', 'TeamController');
                Route::delete('team/destroy/all', 'TeamController@multi_delete')->name('delete_all_team');


                //================== new ==================
                Route::resource('new', 'NewController');
                Route::delete('new/destroy/all', 'NewController@multi_delete')->name('delete_all_new');


                //================== activity_department ==================
                Route::resource('activity_department', 'ActivityDepartmentController');
                Route::delete('activity_department/destroy/all', 'ActivityDepartmentController@multi_delete')->name('delete_all_activity_department');


                //================== activity ==================
                Route::resource('activity', 'ActivityController');
                Route::delete('activity/destroy/all', 'ActivityController@multi_delete')->name('delete_all_activity');
                Route::post('activity/delete_img', 'ActivityController@delete_img')->name('delete_img_activity');


                //================== client ==================
                Route::resource('client', 'ClientController');
                Route::delete('client/destroy/all', 'ClientController@multi_delete')->name('delete_all_client');


                //================== client ==================
                Route::resource('register', 'RegisterController');
                Route::delete('register/destroy/all', 'RegisterController@multi_delete')->name('delete_all_register');



                Route::any('logout', 'AdminAuth@logout');

                });

        });

	//
	// });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::group(
// [
// 	'prefix' => LaravelLocalization::setLocale(),
// 	'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath'],
//    'namespace' => 'Website'
// ], function(){
////


Route::group(['namespace' => 'Website'], function () {

    config(['auth.defaults.guard' => 'web']);

    Route::get('/','HomeController@index');


    Route::get('team_work','PageController@team_work');

/* open courses */
    Route::get('courses','PageController@courses');
    Route::get('course_details/{id}','PageController@course_details');
/* open courses */


/* courses */
    Route::get('courses-by-level/{level_id}','PageController@courses_by_level');
/* courses */


/* activity */
    Route::get('activities-by-activity-department/{activity_department_id}','PageController@activities_by_activity_department');
    Route::get('activity-detail/{activity_id}','PageController@activity_detail');
/* activity */


/* site_text */
    Route::get('site-text','PageController@site_text');
    Route::get('word-of-prestent','PageController@wordOfPrestent');
/* site_text */


    /*=== register ===*/
    Route::post('register','ActionController@register');
    /*=== register ===*/



    Route::get('how_to_study','PageController@how_to_study');
    Route::get('how_to_subscribe','PageController@how_to_subscribe');
    Route::get('news','PageController@news');
    Route::get('contact_us','PageController@contact_us');
    Route::post('send_contact','ActionController@send_contact');
    Route::get('register-with-academy','PageController@register');



    Route::group(['middleware' => ['auth']], function () {



        Route::get('logout','WebAuth@logout');//logout action

    });




});





//Clear route cache:
Route::get('/clear_cache', function() {
//    $exitCode = Artisan::call('route:cache');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');
    return 'cache cleared';
});

app/Models/Activity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
    protected $table = 'activities';
    protected $guarded = [];




    public function activity_department_fk()
    {
        return $this->hasOne('App\Models\ActivityDepartment', 'id', 'activity_department_id');
    }



    public function images_fk() {
        return $this->hasMany('App\Models\Image', 'related_id', 'id');
    }


}

app/Http/Controllers/Admin/ActivityController.php
<?php
namespace App\Http\Controllers\Admin;

// use admin datatable
use App\DataTables\ActivityDatatable;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Activity;
use App\Models\Image;

use Illuminate\Support\Facades\Validator;


class ActivityController extends Controller {


//========================================= index =========================================

    public function index(ActivityDatatable $activity) {
        return $activity->render('admin.activitys.index');
    }



//========================================= create =========================================
    public function create() {
        return view('admin.activitys.create');
    }


//========================================= store =========================================
    public function store(Request $request) {

        $validator = Validator::make(request()->all(),
            [
                'activity_department_id'    => 'required|exists:activity_departments,id',
                'title'                     => 'required',
                'main_image'                => 'required|image',
                'contents'                  => 'nullable',

            ], [], []
        );

        if ($validator->fails()) {
            $errors = collect( $validator->errors() )->flatten(1);
            foreach ($errors as $error) {
                toastr()->warning( $error , trans('admin.Message_title_attention'));
            }
            return back()->withInput();
        }


        $data =  $validator->validated();

        if (request()->main_image != '') {
            $data['main_image']  = upload_image('activitys',request()->main_image, 1, 'main_image');
        }

//        return $data;

        $activity = Activity::create($data);


        if ( request()->hasFile('images') )
        {
            foreach (request()->images as $image )
            {
                $path_ = 'activitys/'.$activity->id;
                $data = upload_multi_images($image, $activity->id,  $path_);
                $add = Image::create([
                    'type'   => 'activities',
                    'related_id' => $activity->id,
                    'image'   => 'activitys/'.$activity->id.'/'. $data['hashname'],
                ]);
            }
        }


        toastr()->success(trans('admin.Message_success'), trans('admin.Message_title_congratulation'));
        return redirect(aurl('activity'));

    }


//========================================= show =========================================
    public function show($id)
    {
        //
    }



//========================================= edit =========================================
    public function edit($id) {

        $activity = Activity::with('images_fk')->find($id);
        return view('admin.activitys.edit', compact('activity'));

    }
//========================================= update =========================================
    public function update(Request $r, $id) {




        $validator = Validator::make(request()->all(),
            [
                'activity_department_id'    => 'required|exists:activity_departments,id',
                'title'                     => 'required',
                'main_image'                => 'nullable|image',
                'contents'                  => 'nullable',

            ], [], []
        );

        if ($validator->fails()) {
            $errors = collect( $validator->errors() )->flatten(1);
            foreach ($errors as $error) {
                toastr()->warning( $error , trans('admin.Message_title_attention'));
            }
            return back()->withInput();
        }


        $data =  $validator->validated();

        if (request()->main_image != '') {
            $data['main_image']  = upload_image('activitys',request()->main_image, 1, 'main_image');
        }


        Activity::where('id', $id)->update($data);


        if ( request()->hasFile('images') )
        {
            foreach (request()->images as $image )
            {
                $path_ = 'activitys/'.$id;
                $data = upload_multi_images($image, $id,  $path_);
                $add = Image::create([
                    'type'   => 'activities',
                    'related_id' => $id,
                    'image'   => 'activitys/'.$id.'/'. $data['hashname'],
                ]);
            }
        }


        toastr()->success(trans('admin.Message_success'), trans('admin.Message_title_congratulation'));
        return redirect(aurl('activity'));

    }



//========================================= destroy =========================================
    public function destroy($id) {

        $activity = Activity::find( $id );
        delete_image($activity->icon);
        $activity->delete();

        toastr()->success(trans('admin.Message_delete'), trans('admin.Message_title_congratulation'));
        $path_ = 'activity';
        return redirect(aurl($path_));

    }

//========================================= multi_delete =========================================
    public function multi_delete() {

        // return request()->all();

        if (is_array(request('item'))) {

            foreach (request('item') as $item)
            {
                $activity = Activity::find( $item );
                delete_image($activity->icon);
            }


            Activity::destroy(request('item'));
        } else {
            $activity = Activity::find( request('item') );
            delete_image($activity->icon);
            $activity->delete();
        }
        toastr()->success(trans('admin.Message_delete'), trans('admin.Message_title_congratulation'));
        $path_ = 'activity';
        return redirect(aurl($path_));

    }



//========================================= destroy =========================================
    public function delete_img(Request $request) {

        $del = Image::find($request->id);
        delete_image($del->image);
        $del->delete();

        return response([
            'status'=>true,
            'title'   => 'اشعار',
            'id'      => $request->id,
            'message' => 'تم حذف الصورة بنجاح'
        ]);

    }



}

resources/views/website/pages/activities/activities_by_activity_department.blade.php
@extends('website.layouts.layout')

@section('page_title')
    {{ (isset($title))? $title:" الاكاديمية " }}
@endsection

@push('web_css')
    <style>
        .head-2
        {
            background: url('{{ GetImg( banner('activities') ? banner('activities')->background : '' ) }}');
        }
    </style>
@endpush

@section('content')



    <section>
        <div class="head-2">
            <div class="overlay"></div>
            <div class="container">
                <div class="head-2-inn head-2-inn-padd-top">
                    <h1>  انشطه {{ $ActivityDepartment->title }} </h1>
                    <div class="event-head-sub">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ url('/') }}">الرئيسية</a></li>
                                <li class="breadcrumb-item active" aria-current="page"> انشطه {{ $ActivityDepartment->title }}</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>




    <!--SECTION START-->
    <section>
        <div class="container com-sp">
            <div class="row">
                <div class="cor about-sp">
                    <div class="ed-about-tit">
                        <div class="con-title">
                            <h2>أنشطة <span> الأكاديمية</span></h2>
                            <p>تقدم الاكاديمية العديد من الانشطة فى كافة المجالات كما تقدم ايضا العديد من الندوات والمؤتمرات وايضا الرسائل والمناقشات </p>
                        </div>
                        <div>
                            <div class="col-md-3">
                                <div class="sidebar sidebar-right mt-sm-30">
{{--                                    <div class="widget">--}}
{{--                                        <h5 class="widget-title line-bottom">بحث عن</h5>--}}
{{--                                        <div class="search-form">--}}
{{--                                            <form>--}}
{{--                                                <div class="input-group">--}}
{{--                                                    <input type="text" placeholder="ابحث عن" class="form-control search-input">--}}
{{--                                                    <span class="input-group-btn">--}}
{{--                      <button type="submit" class="btn search-button"><i class="fa fa-search"></i></button>--}}
{{--                      </span>--}}
{{--                                                </div>--}}
{{--                                            </form>--}}
{{--                                        </div>--}}
{{--                                    </div>--}}

                                    <div class="widget">
                                        <h5 class="widget-title line-bottom">جميع الانشطة</h5>
                                        <div class="categories">
                                            <ul class="list list-border angle-double-right">
                                                @foreach( \App\Models\ActivityDepartment::withCount('activity_departments_fk')->get() as $activity)
                                                    <li><i class="fa fa-angle-double-left"></i><a href="{{ url('activities-by-activity-department').'/'.$activity->id }}">{{ $activity->title }}<span>({{ $activity->activity_departments_fk_count }})</span></a></li>
                                                @endforeach

                                            </ul>
                                        </div>
                                    </div>

                                </div>
                            </div>


                            <div class="col-md-9">
                                <div class="ho-event pg-eve-main">
                                    @foreach($Activities as $activity)
                                        <div class="upcoming-events bg-white-f3 mb-20">
                                            <div class="row">
                                                <div class="col-sm-4 pr-0 pr-sm-15">
                                                    <div class="thumb p-15">
                                                        <img class="img-fullwidth" src="{{ GetImg( $activity->main_image ) }}" alt="...">
                                                    </div>
                                                </div>
                                                <div class="col-sm-4 pl-0 pl-sm-15">
                                                    <div class="event-details p-15 mt-20">
                                                        <h4 class="media-heading text-uppercase font-weight-500">
                                                            {{ $activity->title }}
                                                        </h4>
                                                        <p>
                                                            {{ $activity->contents }}
                                                        </p>
                                                        <a href="{{ url('activity-detail').'/'.$activity->id }}" class="btn btn-flat btn-dark btn-theme-colored btn-sm">لمعرفة التفاصيل <i class="fa fa-angle-double-left"></i></a>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="event-count p-15 mt-15">
                                                        <ul class="event-date list-inline font-16 text-uppercase mt-10 mb-20">
                                                            <li class=" mr-5 bg-lightest">{{ change_Date_into_arabic($activity->created_at , 'full') }}</li>
{{--                                                            <li class="p-15 pl-20 pr-20 mr-5 bg-lightest"> 31</li>--}}
{{--                                                            <li class="p-15 bg-lightest">2015</li>--}}
                                                        </ul>
                                                        <ul>
{{--                                                            <li class="mb-10 text-theme-colored"><i class="fa fa-clock-o mr-5"></i> من الساعة الخامسة : الساعة السابعة</li>--}}
{{--                                                            <li class="text-theme-colored"><i class="fa fa-map-marker mr-5"></i> القاهرة -التجمع الخامس.</li>--}}
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>

                        </div>

{{--                        <div class="pg-pagina">--}}
{{--                            <ul class="pagination">--}}
{{--                                <li class="disabled"><a href="#!"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>--}}
{{--                                <li class="active"><a href="#!">1</a></li>--}}
{{--                                <li class="waves-effect"><a href="#!">2</a></li>--}}
{{--                                <li class="waves-effect"><a href="#!">3</a></li>--}}
{{--                                <li class="waves-effect"><a href="#!">4</a></li>--}}
{{--                                <li class="waves-effect"><a href="#!">5</a></li>--}}
{{--                                <li class="waves-effect"><a href="#!"><i class="fa fa-angle-left" aria-hidden="true"></i></a></li>--}}
{{--                            </ul>--}}
{{--                        </div>--}}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--SECTION END-->



@endsection

resources/views/website/pages/activities/activity_detail.blade.php
@extends('website.layouts.layout')

@section('page_title')
    {{ (isset($title))? $title:" الاكاديمية " }}
@endsection

@push('web_css')
    <style>
        .head-2
        {
            background: url('{{ GetImg( banner('activities') ? banner('activities')->background : '' ) }}');
        }
    </style>
@endpush

@section('content')



    <section>
        <div class="head-2">
            <div class="overlay"></div>
            <div class="container">
                <div class="head-2-inn head-2-inn-padd-top">
                    <h1>   {{ $activity->title }} </h1>
                    <div class="event-head-sub">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ url('/') }}">الرئيسية</a></li>
                                <li class="breadcrumb-item"><a href="{{ url('activities-by-activity-department').'/'.$activity->activity_department_fk->id }}"> {{ $activity->activity_department_fk->title }}</a></li>
                                <li class="breadcrumb-item active" aria-current="page">  {{ $activity->title }}</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>



    <!--SECTION START-->
    <section>
        <div class="container com-sp pad-bot-70 pg-inn">
            <div class="row">
                <div class="cor">

                    <div class="col-md-8">

                        <div class="cor-mid-img">
                            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">

                                    @foreach($activity->images_fk as $key => $image)
                                        <div class="item slider1 {{ $key == 0 ? 'active' : '' }}">
                                            <img src="{{ GetImg( $image->image ) }}" alt="">
                                        </div>
                                    @endforeach

                                </div>

                                <!-- Left and right controls -->
                                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                                    <i class="fa fa-chevron-left slider-arr"></i>
                                </a>
                                <a class="right carousel-control" href="#myCarousel" data-slide="next" style="right: -45px">
                                    <i class="fa fa-chevron-right slider-arr"></i>
                                </a>
                            </div>
                        </div>


                        <div class="cor-con-mid">
                            <div class="cor-p1">
                                <h2>{{ $activity->title }}</h2>
                                <div class="event-info">
                                    <ul>
                                        <li><i class="fa fa-calendar"></i>{{ change_Date_into_arabic($activity->created_at , 'full') }}</li>
{{--                                        <li><i class="fa fa-map-marker"></i> القاهرة - التجمع الخامس</li>--}}
                                    </ul>
                                </div>
                                <div class="share-btn">
                                    <ul>
                                        <li><a href="#"><i class="fa fa-facebook fb1"></i> شارك عبر الفيسبوك</a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-twitter tw1"></i> شارك عبر تويتر</a>
                                        </li>
                                        <li><a href="#"><i class="fa fa-instagram gp1"></i> شارك عبر انستجرام</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="cor-p4">
                                <h3>تفاصيل النشاط:</h3>
                                <p>
                                    {{ $activity->contents }}
                                </p>
{{--                                <ul class="course-li">--}}
{{--                                    <li><i class="fa fa-arrow-left"></i>التسويق باستخدام فيس بوك</li>--}}
{{--                                    <li><i class="fa fa-arrow-left"></i>التسويق باستخدام انستجرام</li>--}}
{{--                                    <li><i class="fa fa-arrow-left"></i>التسويق باستخدام تويتر</li>--}}
{{--                                    <li><i class="fa fa-arrow-left"></i>التسويق باستخدام لينكد ان</li>--}}
{{--                                    <li><i class="fa fa-arrow-left"></i>التسويق باستخدام جوجل ادورد</li>--}}
{{--                                </ul>--}}
                            </div>
                        </div>
                    </div>



                    <div class="col-md-4">
                        <div class="cor-side-com">
                            <div class="ho-ev-latest ho-ev-latest-bg-3">
                                <div class="ho-lat-ev">
                                    <h4>تسجيل الطلاب</h4>
                                    <p> يستطيع الطالب ان يقوم بالتسجيل فى هذا الكورس من هنا وذلك من خلال ملئ الداتا المطلوبة</p>
                                </div>
                            </div>
                            <div class="ho-st-login">
                                <div class="col s12">


                                    <form class="col s12" action="{{ url('register') }}" method="post">
                                        @csrf

                                        <input type="hidden" name="activity_id" value="{{ $activity->id }}">

                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input name="student_name" type="text" class="validate" required>
                                                <label> اسم الطالب </label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input name="qualification" type="text" class="validate" required>
                                                <label> المؤهل الدراسى </label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input name="age" type="text" class="validate" required>
                                                <label> السن </label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input name="address" type="text" class="validate" required>
                                                <label>العنوان </label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input name="phone" type="text" class="validate" required>
                                                <label>رقم الهاتف </label>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input name="email" type="email" class="validate" required>
                                                <label>البريد الالكترونى </label>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="input-field col s12">
                                                <input type="submit" value="تسجيل" class="waves-effect waves-light light-btn">
                                            </div>
                                        </div>

                                    </form>



                                </div>
                            </div>
                        </div>
                    </div>




                </div>
            </div>
        </div>
    </section>
    <!--SECTION END-->



@endsection